#### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
a = np.matrix('1,2;3,4')
b = np.matrix('1,2;3,4')
c = a + b
print(c)

[[2 4]
 [6 8]]


#### 2. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
a = np.matrix('2,4;6,8')
b = np.matrix('2,4;6,8')
c = a * b
print(c)

[[28 40]
 [60 88]]


#### 3. Write a Python Program to Transpose a Matrix?

In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
a = a.reshape(3,3)
print(f'A: \n {a}')
print(f"A transpose: \n {a.transpose()}")

A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A transpose: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
words = input("Enter words: ").split()
words.sort()
print(words)
for i in words:
    print(i,end=' ')

Enter words: cat dog fox elephant animal
['animal', 'cat', 'dog', 'elephant', 'fox']
animal cat dog elephant fox 

#### 5. Write a Python Program to Remove Punctuation From a String?

In [5]:
import string

text = "Hello, World! How are you doing today?"

' '.join(word.strip(string.punctuation) for word in text.split()) 

'Hello World How are you doing today'